"""Init

Revision ID: 6df6ef4ef144
Revises: 
Create Date: 2021-07-24 09:36:04.103062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df6ef4ef144'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('pressform', sa.String(length=50), nullable=False),
    sa.Column('cnt_sockets', sa.String(length=50), nullable=False),
    sa.Column('active_sockets', sa.String(length=50), nullable=False),
    sa.Column('cycle_time', sa.Integer(), nullable=False),
    sa.Column('cycle_active_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'work', 'adjustment', 'smed', 'stop', 'fault', name='sensorstatus'), nullable=False),
    sa.Column('mqtt_label', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('sensors')
    # ### end Alembic commands ###
